### ISSUE TITLE
Sol-Bash

### ISSUE THREAD

**Issue by Bhaney44** [ChoiceCoin/Compliance#1]
**Rewards**
Gold Badge | 300,000.00 Choice
Silver Badge | 150,000.00 Choice
Bronze Badge | 50,000.00 Choice

Winners will be announced by June 12th at 6:00PM EST.

**Details**
Deadline: June 10th at 6:00PM EST.

Write a program using the Solana Javascript-SDK that integrates the functionality of the [Choice Coin Solana Compliance Software](https://github.com/ChoiceCoin/Solana-Compliance/blob/main/Software/v1/SolanaStatisticalCompliance.py). The software should allow for a frontend web interface that allows a user to enter data for each factor and then push a `Calculate Compliance Score` button to return a result between 0 and 1. The score should also be sent to an arbitrary address on the Solana blockchain as a message. As few files as possible should be used for the code. 

A `readme.md` file should be included. All files must be in one folder, titled `username_solbash`and added to the [SolBash](https://github.com/ChoiceCoin/Compliance/tree/main/SolBash) folder. All PRs must be titled `username_solanabash`. Preference will be given to projects with screenshots or video demos. The goal for submissions should be simplicity - the simpler the better. Any questions may be asked in the comments below or on Discord.

**Comment by terrykeng** [comment]
What kind of data can the user input?

**Comment by ChoiceCoin** [comment]
> What kind of data can the user input?

It should be this dictionary.

`natural_language_compression = {'good':0.75, 'acceptable':0.5, 'outstanding': 1, 'unacceptable': 0, 'marginal': .25}`

**Comment by terrykeng** [comment]
So the user inputs for each factor if it’s good, acceptable, outstanding, unacceptable or marginal and the ai computes the compliance score

**Comment by terrykeng** [comment]
For the message can it be sent as a note in a transaction?

**Comment by Bhaney44** [comment]
> For the message can it be sent as a note in a transaction?

Yes.

**Comment by Bhaney44** [comment]
> So the user inputs for each factor if it’s good, acceptable, outstanding, unacceptable or marginal and the ai computes the compliance score

Yes.

**Comment by terrykeng** [comment]
I want to try implementing the Choice coin compliance software in js instead of python so It'll be a lot more easier for my frontend to  interact with the blockchain

**Comment by Bhaney44** [comment]
> I want to try implementing the Choice coin compliance software in js instead of python so It'll be a lot more easier for my frontend to interact with the blockchain

You can use JavaScript or Python for the compliance software.

**Comment by dhanzy** [comment]
@Bhaney44 can we rewrite the compliance software with javascript.

**Comment by Bhaney44** [comment]
> @Bhaney44 can we rewrite the compliance software with javascript.

Yes.

**Comment by prince-hope1975** [comment]
What is the range of the compliance input, from what to what????

**Comment by Bhaney44** [comment]
> What is the range of the compliance input, from what to what????

It should be this dictionary.

`natural_language_compression = {'good':0.75, 'acceptable':0.5, 'outstanding': 1, 'unacceptable': 0, 'marginal': .25}`

**Comment by Bhaney44** [comment]
**Winner**
First prize and Gold Badge @dhanzy
